# -*- coding: utf-8 -*-
"""
Created on Wed Dec 27 15:55:18 2017

@author: paulo
"""
CROSSOVER_RATE = 0.9 #RATE OF CROSSOVER
MUTATION_RATE = 0.001 #RATE OF MUTATION
POP_SIZE = 100 #POPULATION SIZE
N_GENERATIONS = 1000 #MAXIMUM NUMBER OF GENERATIONS
CHRM_SIZE = 64 #CHROMOSSOME SIZE IN BITS